# Generated by Django 4.0.1 on 2022-01-31 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_auctions_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
