# Generated by Django 4.0.1 on 2022-01-31 01:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='seller',
            field=models.ManyToManyField(related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
