# Generated by Django 4.0.1 on 2022-02-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_auction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
