# Generated by Django 4.0.1 on 2022-02-05 04:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_auction_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='current_bid',
            new_name='bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auction'),
        ),
    ]
