# Generated by Django 4.0.1 on 2022-02-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(default='Open', max_length=7),
        ),
    ]
