# Generated by Django 4.0.1 on 2022-02-09 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_comments_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
