# Generated by Django 4.0.1 on 2022-02-10 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_rename_comments_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='starting_price',
            new_name='price',
        ),
    ]
